name: GitHub Actions Sample
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'
jobs:
  # This workflow contains a single job called "build"
  build:
    name: flutter build
    runs-on: macos-latest
    steps:
      - run: echo "Hello world"