name: GitHub Actions Sample
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Experimenting
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - name: multiline
        run: |
          echo "Hello multiline script"
          brew install --cask flutter
          flutter --version
          flutter pub get
          flutter analyze
          flutter build macos
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: macos-scrptr
          path: build/macos/Build/Products/Release
