name: GitHub Actions Sample
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Experimenting
    runs-on: macos-latest
    steps:
      - run: echo "Hello world"
      - name: multiline
        run: |
          echo "Hello multiline script"
          brew install --cask flutter
          flutter --version
        shell: bash
